//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UGNITE {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UGNITE.en", typeof(en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ACHIEVEMENTS.
        /// </summary>
        internal static string btnAchievements {
            get {
                return ResourceManager.GetString("btnAchievements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a UNINSTALL GAME.
        /// </summary>
        internal static string btnDeleteGame {
            get {
                return ResourceManager.GetString("btnDeleteGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a INSERT.
        /// </summary>
        internal static string btnInsertAchievement {
            get {
                return ResourceManager.GetString("btnInsertAchievement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a YOUR LIBRARY.
        /// </summary>
        internal static string btnLibrary {
            get {
                return ResourceManager.GetString("btnLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a UGNITE GAMES INSTALLATION.
        /// </summary>
        internal static string btnLibrary0 {
            get {
                return ResourceManager.GetString("btnLibrary0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a STARTUP REPAIR.
        /// </summary>
        internal static string btnStartupRepair {
            get {
                return ResourceManager.GetString("btnStartupRepair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a STORE.
        /// </summary>
        internal static string btnStore {
            get {
                return ResourceManager.GetString("btnStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a UPDATE INFO.
        /// </summary>
        internal static string btnUpdateInformation {
            get {
                return ResourceManager.GetString("btnUpdateInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a UPDATE.
        /// </summary>
        internal static string btnUpdatePassword {
            get {
                return ResourceManager.GetString("btnUpdatePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a UPDATE MY IMAGE.
        /// </summary>
        internal static string btnUploadImage {
            get {
                return ResourceManager.GetString("btnUploadImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a YOUR ACTIVITY.
        /// </summary>
        internal static string btnYourActivity {
            get {
                return ResourceManager.GetString("btnYourActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a BUY WITH UPAY.
        /// </summary>
        internal static string BuyWithUpay {
            get {
                return ResourceManager.GetString("BuyWithUpay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SIGN UP.
        /// </summary>
        internal static string cadastrar {
            get {
                return ResourceManager.GetString("cadastrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a NEW USER SIGN UP.
        /// </summary>
        internal static string cadastro_de_usuario {
            get {
                return ResourceManager.GetString("cadastro_de_usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SAVE LOGIN INFORMATION.
        /// </summary>
        internal static string checkSaveLogin {
            get {
                return ResourceManager.GetString("checkSaveLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a DEVELOPERS OR PUBLISHERS.
        /// </summary>
        internal static string devpublisher {
            get {
                return ResourceManager.GetString("devpublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a LOGIN.
        /// </summary>
        internal static string entrar {
            get {
                return ResourceManager.GetString("entrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a FORGOT PASSWORD :(.
        /// </summary>
        internal static string esquecisenha {
            get {
                return ResourceManager.GetString("esquecisenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a USER ID.
        /// </summary>
        internal static string identificacao {
            get {
                return ResourceManager.GetString("identificacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a UGNITE+ | 14 Days.
        /// </summary>
        internal static string lb14Days {
            get {
                return ResourceManager.GetString("lb14Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a UGNINTE+ | 1 Month.
        /// </summary>
        internal static string lb30Days {
            get {
                return ResourceManager.GetString("lb30Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ACHIEVEMENT DESC.
        /// </summary>
        internal static string lbAchievementDescription {
            get {
                return ResourceManager.GetString("lbAchievementDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ACHIEVEMENT IMAGE (128X128) VIA URL.
        /// </summary>
        internal static string lbAchievementIMG {
            get {
                return ResourceManager.GetString("lbAchievementIMG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ACHIEVEMENT NAME.
        /// </summary>
        internal static string lbAchievementName {
            get {
                return ResourceManager.GetString("lbAchievementName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ACHIEVEMENTS PANEL.
        /// </summary>
        internal static string lbAchievementsPanel {
            get {
                return ResourceManager.GetString("lbAchievementsPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a DEVELOPER PANEL.
        /// </summary>
        internal static string lbDeveloperPanel {
            get {
                return ResourceManager.GetString("lbDeveloperPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a USER ACCOUNT SETTINGS.
        /// </summary>
        internal static string lbDialogAbout {
            get {
                return ResourceManager.GetString("lbDialogAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a AVAILABLE ACHIEVEMENTS FOR YOUR GAMES.
        /// </summary>
        internal static string lbGameAchievements {
            get {
                return ResourceManager.GetString("lbGameAchievements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ACHIEVEMENT ID (AUTO).
        /// </summary>
        internal static string lbGeneratedID {
            get {
                return ResourceManager.GetString("lbGeneratedID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a IMAGE URL.
        /// </summary>
        internal static string lbImageURL {
            get {
                return ResourceManager.GetString("lbImageURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a INSERT ACHIEVEMENTS.
        /// </summary>
        internal static string lbInsercoes {
            get {
                return ResourceManager.GetString("lbInsercoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a PUT THE 25 KEY CODE BELOW.
        /// </summary>
        internal static string lbKeyCode {
            get {
                return ResourceManager.GetString("lbKeyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a LAST ACTIVITIES MADE AT UGNITE.
        /// </summary>
        internal static string lbLastActivities {
            get {
                return ResourceManager.GetString("lbLastActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a NEW PASSWORD.
        /// </summary>
        internal static string lbNewPass {
            get {
                return ResourceManager.GetString("lbNewPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a THE DAYS WILL BE HELD IF YOU ALREADY HAVE AN ACTIVE UGNITE+ PLAN.
        /// </summary>
        internal static string lbPlusInfos {
            get {
                return ResourceManager.GetString("lbPlusInfos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a UGNITE+ PLANS.
        /// </summary>
        internal static string lbPlusPlans {
            get {
                return ResourceManager.GetString("lbPlusPlans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a UGNITE SECURE CODE.
        /// </summary>
        internal static string lbSecurityCode {
            get {
                return ResourceManager.GetString("lbSecurityCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT GAME TARGET.
        /// </summary>
        internal static string lbSelectGameTarget {
            get {
                return ResourceManager.GetString("lbSelectGameTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ALLOWED OPERATIONS USING UAPI.
        /// </summary>
        internal static string lbStatusOperacoes {
            get {
                return ResourceManager.GetString("lbStatusOperacoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a THEME.
        /// </summary>
        internal static string lbTheme {
            get {
                return ResourceManager.GetString("lbTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a TO UPDATE ANY INFORMATION AT YOUR ACCOUNT YOU&apos;LL NEED THE UGNITE SECURE CODE. IF YOU LOST IT, CONTACT US BY E-MAIL: shop@ironiawn.com.br.
        /// </summary>
        internal static string lbUpdateAlert {
            get {
                return ResourceManager.GetString("lbUpdateAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a USER E-MAIL.
        /// </summary>
        internal static string lbUsermail {
            get {
                return ResourceManager.GetString("lbUsermail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a PLEASE WAIT WHILE UGNITE INSTALLS YOUR GAME.
        /// </summary>
        internal static string lbWarning {
            get {
                return ResourceManager.GetString("lbWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a YOUR ACHIEVEMENTS AT UGNITE.
        /// </summary>
        internal static string lbYourAchievements {
            get {
                return ResourceManager.GetString("lbYourAchievements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a USER LOGIN.
        /// </summary>
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SIGN UP.
        /// </summary>
        internal static string novouser {
            get {
                return ResourceManager.GetString("novouser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a RETRIEVE GAME ACTIVATION KEY.
        /// </summary>
        internal static string resgatarchave {
            get {
                return ResourceManager.GetString("resgatarchave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a PASSWORD.
        /// </summary>
        internal static string senha {
            get {
                return ResourceManager.GetString("senha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a I&apos;M A DEV/PUBLISHER.
        /// </summary>
        internal static string soudev {
            get {
                return ResourceManager.GetString("soudev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a TERMS OF USE.
        /// </summary>
        internal static string termos {
            get {
                return ResourceManager.GetString("termos", resourceCulture);
            }
        }
    }
}
